name: Run checks

on:
  workflow_call:
    inputs:
      push_coverage:
          type: boolean
          description: "If true, the coverage results are pushed to codecov.io."
          default: true
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  run-checks:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: uv sync --frozen --all-extras
      - name: Run styling check
        run: uv run --no-sync pre-commit run --all-files
      - name: Launch background worker
        run: |
          uv run --no-sync python docling_jobkit/orchestrators/rq/worker.py &
          echo "Worker started in background with PID $!"
          echo "WORKER_PID=$!" >> $GITHUB_ENV
      - name: Testing
        run: |
          uv run --no-sync pytest -v --cov=docling_jobkit --cov-report=xml tests
      - name: Terminate background worker
        if: always()
        run: |
          kill ${{ env.WORKER_PID }}
          echo "Worker with PID ${{ env.WORKER_PID }} terminated."
      - name: Upload coverage to Codecov
        if: inputs.push_coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
